### PR TITLE
Added Github Action

### LINKED ISSUE #20: Github actions for project enhancements
Github actions for project enhancements
Before assigning let me know what kind of action will you implement in the project.

### PR DESCRIPTION
**Pull request by Aayush-hub**
### What is the change?
Added Github Action for enhancement of project.

### What does it fix/add?
Fixes: #20 Github actions for project enhancements

## Submissions guide:
- [x] Have you followed the Contribution guidelines?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/akshitagupta15june/vehicle_speed_estimator/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam, please review my contribution for NWOC.

**Comment by akshitagupta15june** [comment]
Great!

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam please update my points for NWOC!

**Comment by akshitagupta15june** [comment]
ok done!

**Pull request merged**
