### PR TITLE
Added PR for number plate detection

### LINKED ISSUE #1: Features of vehicle plate Detection
Features enhancement

### PR DESCRIPTION
**Pull request by Aayush-hub**
### What is the change?
Added PR which detects Number plates of car using Opencv.

### What does it fix/add?
Fixes: #1 Features of vehicle plate Detection

### How was it tested?
Tested by Contributor personally.

## Submissions guide:
- [x] Have you followed the Contribution guidelines?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/akshitagupta15june/vehicle_speed_estimator/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
Capture
Capture2
Capture3

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam, please review my PR.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
output images not visible in readme.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Solved!

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam, Is there any extra points for creating a PR for solving a specific issue??

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam the problem is readme file is solved!

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
great work @Aayush-hub !
will be updating your points.

**Pull request merged**
