### PR TITLE
Added GUI for displaying results.

### LINKED ISSUE #7: Develop a Python GUI for displaying Results.
Develop a Python GUI for displaying Results.
A Interactive GUI application using python (Tkinter) to show results

### PR DESCRIPTION
**Pull request by Aayush-hub**
### What is the change?
Added GUI for displaying results and updated Readme.md

### What does it fix/add?
Fixes: #7 Develop a Python GUI for displaying Results.

### How was it tested?
Tested locally by contributor many times.

## Submissions guide:
- [x] Have you followed the Contribution guidelines?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/akshitagupta15june/vehicle_speed_estimator/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### Screenshots :
Capture

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam please review my PR as a NWOC participant:)

**Comment by akshitagupta15june** [comment]
that is great merging your pr.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you create a seprate folder for this gui then add your commits.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Yes sure mam:)

**Review by akshitagupta15june — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
AWESOME!

**Comment by akshitagupta15june** [comment]
I WILL UPDATE YOUR POINTS

**Comment by Aayush-hub** [comment]
@akshitagupta15june Thank you mam!

**Pull request merged**
